version: '3.8'

services:
  pocket-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-}
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY:-}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Optional: persist logs
      - ./logs:/app/logs
    networks:
      - pocket-app-network

networks:
  pocket-app-network:
    driver: bridge
